### ISSUE TITLE
question about the frame annotation

### ISSUE THREAD

**Issue by azhuantou** [epic-kitchens/epic-kitchens-55-annotations#25]
Hi,Thanks  for  the release of this dataset.
In EPIC_video_info.csv,duration of P29_03 is 2074.672583,and fps is 59.9400599400599. So total frame is duration*fps= 124355.But in EPIC_train_action_labels.csv,uid 35757,35758 and 35759,their start_frame and stop_frame is bigger than 124355.The same thing happens in other videos.Is this a mistake?

**Comment by azhuantou** [comment]
P10_04 in EPIC_train_action_labels.csv(uid 16882-16898) have the same problem.

**Comment by dimadamen** [comment]
As noted in our journal paper: https://arxiv.org/abs/2005.00343
in Section 3.1 (note the footnote on page 3), 2.2% of the videos were recorded at a different frame rate. We thus offer RGB JPEG frames at a resolution of 456x256 resampled to 60fps for all videos to unify these. The original videos are provided as captured.
All the video fps and resolution are found in: https://github.com/epic-kitchens/epic-kitchens-55-annotations/blob/master/EPIC_video_info.csv
